/** @type {import('tailwindcss').Config} */
export default {
  content: ['./index.html', './src/**/*.{vue,js,ts,jsx,tsx}'],
  theme: {
    screens: {
      xs: '320px',
      sm: '500px',
      md: '768px',
      lg: '1024px',
      xl: '1440px',
    },
    colors: {
      transparent: 'transparent',
      current: '#000000',
      orange: '#ff642f',
      rose: '#ffd7c9',
      lightblue: '#e3f1ff',
      black: '#000000',
      gray: '#7f7f7f',
      lightgray: '#e8e8e8',
      white: '#f9f9f9',
    },
    fontSize: {
      xs: '0.5rem',
      sm: '0.75rem',
      md: '0.9rem',
      base: '1rem',
      lg: '1.1rem',
      xl: '1.25rem',
      '1.5xl': '1.5rem',
      '2xl': '2rem',
      '2.5xl': '2.5rem',
      '3xl': '3rem',
      '3.5xl': '3.5rem',
      '4xl': '4rem',
      '4.5xl': '4.5rem',
      '5xl': '5rem',
    },
    fontFamily: {
      playfair: ['Playfair Display', 'serif'],
    },
    extend: {},
  },
  plugins: [],
}
